import React from "react"
import Link from "next/link"

export function Footer() {
  return (
    <footer className="w-full bg-card/45 border-t border-border/40 py-8 px-4 sm:px-6 mt-12 font-sans select-none text-[10px]">
      <div className="max-w-6xl mx-auto flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
        
        {/* Left Column: Legal Risk Disclaimers & Branding */}
        <div className="max-w-xl space-y-2">
          <div className="flex items-center gap-2">
            <span className="font-bold tracking-widest text-foreground uppercase">YieldWatch</span>
            <span className="text-muted-foreground/60">|</span>
            <span className="text-muted-foreground">Portfolio Analytics</span>
          </div>
          <p className="text-muted-foreground/75 leading-relaxed text-justify">
            <strong>Regulatory & Risk Disclosure:</strong> YieldWatch is a personal financial tracking tool designed for educational and informational purposes only. We are not registered as a broker-dealer or investment advisor with any financial authority. No content, calculations, safety scores, or trend signals generated by this platform constitute a recommendation to buy, hold, or sell any security. All stock evaluations are mathematical outputs based on historical parameters and do not account for future market shifts. Dividend payments are subject to board approvals and are never guaranteed. Past yield performance is not illustrative of future returns.
          </p>
          <p className="text-muted-foreground/50 font-mono">
            © {new Date().getFullYear()} YieldWatch. All rights reserved.
          </p>
        </div>

        {/* Right Column: Policy Links */}
        <div className="flex flex-col sm:flex-row gap-4 sm:gap-6 shrink-0 font-mono uppercase tracking-wider font-bold">
          <Link
            href="/terms"
            className="text-muted-foreground hover:text-foreground transition-colors"
          >
            Terms & Conditions
          </Link>
          <Link
            href="/privacy"
            className="text-muted-foreground hover:text-foreground transition-colors"
          >
            Privacy Policy
          </Link>
          <a
            href="https://shares-yieldwatch.vercel.app/"
            target="_blank"
            rel="noopener noreferrer"
            className="text-muted-foreground hover:text-foreground transition-colors"
          >
            Live Demo
          </a>
        </div>

      </div>
    </footer>
  )
}
